name: Analyze Pull Request

# then define on which event, here a pull request on all branches
on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: [self-hosted, coax]
    steps:
      - name: 'Checkout repository on branch: ${{ github.REF }}'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.REF }}
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Define Node version
      - name: Install packages
        run: npm ci
      - name: Run Linter
        run: npm run lint:cov
      - name: Run Tests
        run: npm run test:cov
        env:
          NODE_OPTIONS: "--max_old_space_size=3072"
